import React from 'react'
import Navbar from './Components/Navbar'
import Homepage from './Components/Homepage'

const App = () => {
  return (
    <div>
      <Navbar/>
      <Homepage/>
      <div className="min-h-[90vh]">
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
        <p>jfkla;fsdjfkj</p>
      </div>
    </div>
  )
}

export default App
